MODEL:
  INIT_WEIGHTS: true
  NAME: 'pose_resnet'
  PRETRAINED: 'marco\data\resnet50-19c8e357.pth'
  IMAGE_SIZE:
  - 288
  - 384
  HEATMAP_SIZE:
  - 72
  - 96
  SIGMA: 3
  NUM_JOINTS: 17
  TARGET_TYPE: 'gaussian'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    DECONV_WITH_BIAS: false
    NUM_DECONV_LAYERS: 3
    NUM_DECONV_FILTERS:
    - 256
    - 256
    - 256
    NUM_DECONV_KERNELS:
    - 4
    - 4
    - 4
    NUM_LAYERS: 50